name: 'Coverity output-v7-json Report'
description: 'Parse Coverity output-v7-json and report on the results within GitHub'
author: 'Synopsys Inc'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
